### ISSUE TITLE
Zoznam dlznikov Socialna poistovna

### ISSUE THREAD

**Issue by jsuchal** [OpenDataSk/data-requests#1]
> Dobry den,
> 
> chcel by som sa spytat preco je zoznam dlznikov http://www.socpoist.sk/zoznam-dlznikov-emw/487s chraneny systemom CAPTCHA? Nevidim na to najmensi dovod, proti ziadnemu spamu sa tu chranit nepotrebujete.
> 
> Mimochodom CAPTCHA bez alternativy je porusenim vynosu MF o ISVS a taktiez Vami deklarovanej kompatibility s BlindFriendly http://blindfriendly.unss.sk/blind-friendly-web-navod.php, ktoru mate v paticke kazdej podstranky socpoist.sk
> 
> S pozdravom
> Jan Suchal

**Comment by jsuchal** [comment]
> Dobrý deň,
> 
> systém CAPTCHA je na stránke kvôli odfiltrovaniu automatizovaných skriptov, ktoré by chceli stiahnuť celý zoznam dlžníkov. Čo sa týka pravidiel pre Blind Friendy, riešením je nasadiť iný typ CAPTCHA. Sociálna poisťovňa túto možnosť v najbližšom období zabezpečí.
> 
> S pozdravom

**Comment by jsuchal** [comment]
> Dobry den,
> 
> dakujem za odpoved, ale nerozumiem preco su pre Vas problem automatizovane skripty, ktore to stahuju?
> Viete mi vysvetlit preco sa tomu vlastne branite? 
> 
> V klude mi zavolajte na XXXX XXX XXX, bude to rychlejsie. 
> 
> S pozdravom
> Jan Suchal

**Comment by jsuchal** [comment]
> Dobrý deň,
> 
> v suvislosti s Vasou dodatocnou otazkou Vam zasielam nasledovne vyjadrenie:
> 
> Ochrana pred automatizovanými skriptami je opodstatnená, nakoľko v predchádzajúcom období 
> (z dôvodu zníženia výšky sumy, pri ktorej sa klient SP považuje za neplatiča a tym zvyseniu
> poctu zobrazovanych a spracovavanych udajov) došlo k náhlemu zahlteniu servera práve predmetnými automatizovanymi skriptami, čo spôsobilo nedostupnosť služby. Z toho dôvodu sme pristúpili k implementacii sposobu ochrany uvedeným spôsobom. Sledujeme tým minimalizovanie  a rovnomerne rozlozenie záťaže na server a zabezpečenie dostupnosti služby všetkým klientom. 
> Systém CAPTCHA budeme v blízkej dobe upgradovať.
> 
> Dakujem za porozumenie
> 
> S pozdravom

**Comment by jsuchal** [comment]
> Dobry den,
> 
> nebolo by jednoduchsie vypublikovat staticky subor, ktory sa bude generovat kazdy
> den/tyzden/mesiac a obsahoval by komplet data v strojovo spracovatelnej forme?
> CSV? Takto to robi vseobecna zdravotna poistovna, danove riaditelstvo, statisticky urad,
> nakoniec by ste to aj tak mohli publikovat na data.gov.sk ak mate problem so zatazou... 
> prikladov len na Slovensku je vela.
> 
> Hlavne v kontexte open data iniciativ, ktore k vam skor ci neskor pridu ako uz schvalene
> nariadenie z EU mi pride toto ako uplne kontraproduktivne. Tie data budete skor ci neskor
> vypublikovat kompletne a strojovo spracovatelne, branit sa tomu je uplne zbytocne a vlastne
> proti zaujmom obcanov.
> 
> Taktiez by sam Vam rad povedal, ze CAPTCHA v ziadnom pripade nezabrani automatickemu stahovaniu dat, cesta sa vzdy najde. Jedine co sposobite je, ze napor na vas web bude este vacsi, lebo to bude chciet viac "vypoctovej" sily. Ak by ste spravili presny opak a poskytli cely zoznam priamo, nikto vam server vytazovat dalsimi dopytmi nebude zbytocne. Bavime sa tu inak o subore ktory by mal par MB, co v dnesnej dobe je naozaj smiesne.
> 
> V klude mi zavolajte na XXXX XXX XXX, tento problematike sa venujem uz dlho a velmi rad vam poradim a v klude Vam aj ukazem ako tu CAPTCHU co tam teraz mate obidem.
> 
> S pozdravom
> Jan Suchal

**Comment by jsuchal** [comment]
> Dobry den,
> 
> dakujem za Vase namety a pripomienky, budeme sa nimi zaoberat v zmysle nasich technickych
> moznosti a internych predpisov.
> 
> S pozdravom

**Comment by jsuchal** [comment]
> Dobry den,
> dovolte mi informovat Vas, ze moznost hromadneho downloadu zoznamu dlznikov vo formate
> .csv a .txt bol po testovani nasadeny do ostrej prevadzky v piatok 24.1.2014.
> 
> http://www.socpoist.sk/zoznam-dlznikov-emw/487s
> 
> Zaroven CAPTCHA na strankach www.socpoist.sk bola prisposobena tak, aby splnala
> vynos MF SR o standardoch ISVS c. 312/2010 Z.z..
> 
> S pozdravom

**Comment by hanecak** [comment]
Nuz, to catcha nebrani downloadu CSV-cka, takze fakt success. Zatvaram.
