### ISSUE TITLE
Projekt prepojenia električkových radiál

### ISSUE THREAD

**Issue by ghost** [OpenDataSk/data-requests#3]
Adresát: Magistrát hlavného mesta SR Bratislavy, Primaciálne nám. 1,
P. O. Box 192, 814 99 Bratislava 1, pulcova@bratislava.sk,
sluzbyobcanom@bratislava.sk
Žiadateľ: Cyklokoalícia, Karadžičova 6, 82108 Bratislava, info@cyklokoalicia.sk

Dobrý deň,

uznesením Mestského zastupiteľstva hlavného mesta SR Bratislavy č.
779/2012 zo dňa 26.-27. 09. 2012. bol schválený bod  Rozvoj a
modernizácia nosného systému mestskej hromadnej dopravy v rámci
Operačného programu doprava, IV prioritná os: mesto Bratislava,
ktorého súčasťou je "Dobudovanie viacpásmového prepojenia
električkových radiál - Račianskej, Vajnorskej a Ružinovskej radiály
prostredníctvom dobudovania električkovej trate cez Zátišie - Pluhovú
a Tomášikovu úľ. v trase Račianska - Pluhová (Zátišie) - Vajnorská -
Trnavská - Ružinovská" (ďalej len "Projekt prepojenia električkových
radiál").

Na základe zákona č. 211/2000 Z. z. o slobodnom prístupe k informáciám
v znení neskorších predpisov žiadame o nasledovné informácie:
1. Aký je stav predprojektovej a projektovej prípravy, obstarávania, a
   realizácií v súvislosti s Projektom prepojenia električkových radiál?
2. Aký je schválený harmonogram Projektu prepojenia električkových radiál?
3. Aké plány a technická dokumentácia sú vypracované pre Projekt
   prepojenia električkových radiál?

Informáciu žiadame zaslať v elektronickej podobe na našu emailovú
adresu info@cyklokoalicia.sk .

V zmysle pár. 14 ods 5. zákona žiadame o potvrdenie prijatia žiadosti
o informácie.

Ďakujem,
Michal Malý
Cyklokoalícia

**Comment by cyklokoalicia** [comment]
Dobrý deň pán Malý,

na Vaše otázky zo dňa 4.2.2014, v zmysle zákona č. 211/2000 Z.z. o slobodnom prístupe k informáciám, poskytujem tieto odpovede:
1. Prepojenie električkových radiál sa najskôr v ich technickom riešení bude študovať v územnom genereli dopravy. Preto nie je začatá ani predprojektová príprava a ani ďalšie stupne projektových či administratívnych krokov.
   2.Harmonogram vzíde z prognostickej časti územného generelu dopravy.
2. Žiadne.

s úctou

T. S.
