### ISSUE TITLE
CRZ open data

### ISSUE THREAD

**Issue by jsuchal** [OpenDataSk/data-requests#8]
![image](https://cloud.githubusercontent.com/assets/26342/13234079/335ad466-d9b7-11e5-886e-2063a9fbc5bd.png)

**Comment by hanecak** [comment]
23.6.2016 pridali na data.gov.sk zaznam o dostupnosti dennych zmenovych davok z ZIP/XML:

https://data.gov.sk/dataset/crz/resource/ddb5a2dc-d0fe-4fd9-b939-994d35b9487f

API zrejme zatial nespustili: https://platforma.slovensko.digital/t/centralny-register-zmluv-api/1383

**Comment by jsuchal** [comment]
@hanecak podla mna ani ziadne API v plane nie je. Su tam tie denne exporty. Ja by som toto zatvoril.

**Comment by hanecak** [comment]
K datasetu pridali okrem zmenovych davok aj RSS (aj ked uvedena linka dnes neplati, da sa najst ina).

Zmenove davky funguju, to je asi gro: https://data.gov.sk/dataset/crz/resource/ddb5a2dc-d0fe-4fd9-b939-994d35b9487f

Takze zatvaram.
